server:
  port: 8761
eureka:
  server:
    peer-node-read-timeout-ms: 300000
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
    root: INFO
spring:
  application:
    name: Discovery
